version: '3'
services:
  web:
    tty: true
    build: .
    image: ubuntu:14.04-php5.5.9
    ports:
     - "80:80"
    volumes:
     # php日志映射
#     - /Users/CsHeng/Downloads/log:/tmp
     # nginx/php-fpm/supervisor日志映射
#     - /Users/CsHeng/Downloads/log:/var/log
     # 代码文件夹映射，注意修改nginx default conf
#     - /Users/CsHeng/Workspace/Web/server-api:/www/api
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/sites-enabled/default:/etc/nginx/sites-enabled/default
#     - ./php5/fpm/php.ini:/etc/php5/fpm/php.ini
     - ./php5/fpm/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
     - ./php5/fpm/pool.d/www.conf:/etc/php5/fpm/pool.d/www.conf
